scrape_configs:

  - job_name: 'innosistemas'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['innosistemas:8082']

  - job_name: 'notifications'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notifications:8083']

  - job_name: 'authenticator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['authenticator:8081']

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']