[build]
builder = "nixpacks"
buildCommand = "chmod +x ./mvnw && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/authenticator-0.0.1-SNAPSHOT.jar"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
